import { spawnSync } from 'node:child_process';
import { chmodSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { Octokit } from '@octokit/rest';

import type { Answers } from '../config.js';

// The ESM build of libsodium-wrappers is broken (missing libsodium.mjs), so
// load the CommonJS build explicitly.
const require = createRequire(import.meta.url);
const sodium = require('libsodium-wrappers') as typeof import('libsodium-wrappers');

export class GitHubError extends Error {}

export interface GitHubContext {
  octokit: Octokit;
  owner: string;
  ownerId: number;
  repo: string;
  repoPrivate: boolean;
}

export async function createContext(answers: Answers): Promise<GitHubContext> {
  const octokit = new Octokit({ auth: answers.github.token });
  let login: string;
  let ownerId: number;
  try {
    const { data } = await octokit.users.getAuthenticated();
    login = data.login;
    ownerId = data.id;
  } catch {
    throw new GitHubError(
      'GitHub rejected the token. It needs the "repo" and "workflow" scopes ' +
        '(classic PAT) or equivalent fine-grained permissions.',
    );
  }
  return {
    octokit,
    owner: login,
    ownerId,
    repo: answers.github.repoName,
    repoPrivate: answers.github.repoPrivate,
  };
}

/** Create the repository, or reuse it when it already exists. */
export async function ensureRepo(ctx: GitHubContext): Promise<{ created: boolean; url: string }> {
  try {
    const { data } = await ctx.octokit.repos.get({ owner: ctx.owner, repo: ctx.repo });
    if (!data.permissions?.push) {
      throw new GitHubError(
        `Repository ${ctx.owner}/${ctx.repo} exists but the token cannot push to it.`,
      );
    }
    return { created: false, url: data.html_url };
  } catch (error) {
    if (error instanceof GitHubError) throw error;
    if ((error as { status?: number }).status !== 404) throw error;
  }
  const { data } = await ctx.octokit.repos.createForAuthenticatedUser({
    name: ctx.repo,
    private: ctx.repoPrivate,
    description: 'Serverless infrastructure on Scaleway, generated by keel',
    has_wiki: false,
    has_projects: false,
    auto_init: false,
  });
  return { created: true, url: data.html_url };
}

/**
 * Push the generated repo over HTTPS. The token is handed to git through a
 * temporary GIT_ASKPASS helper reading an environment variable, so it never
 * appears in the remote URL, in .git/config or in the process list.
 */
export function pushRepo(ctx: GitHubContext, token: string, targetDir: string): void {
  const remoteUrl = `https://github.com/${ctx.owner}/${ctx.repo}.git`;
  const askpassDir = mkdtempSync(join(tmpdir(), 'keel-askpass-'));
  const askpass = join(askpassDir, 'askpass.sh');
  writeFileSync(askpass, '#!/bin/sh\necho "$KEEL_GIT_TOKEN"\n');
  chmodSync(askpass, 0o700);
  try {
    const git = (args: string[]) =>
      spawnSync('git', args, {
        cwd: targetDir,
        stdio: ['ignore', 'pipe', 'pipe'],
        env: {
          ...process.env,
          GIT_ASKPASS: askpass,
          KEEL_GIT_TOKEN: token,
          GIT_TERMINAL_PROMPT: '0',
        },
      });
    git(['remote', 'remove', 'origin']);
    const addRemote = git(['remote', 'add', 'origin', remoteUrl]);
    if (addRemote.status !== 0) {
      throw new GitHubError(`git remote add failed: ${addRemote.stderr.toString().trim()}`);
    }
    // The remote embeds the username only; the password comes from askpass.
    const setUser = git(['config', 'credential.username', 'x-access-token']);
    if (setUser.status !== 0) {
      throw new GitHubError(`git config failed: ${setUser.stderr.toString().trim()}`);
    }
    const push = git(['push', '-u', 'origin', 'main']);
    if (push.status !== 0) {
      throw new GitHubError(`git push failed: ${push.stderr.toString().trim()}`);
    }
  } finally {
    rmSync(askpassDir, { recursive: true, force: true });
  }
}

/** Encrypt and upload every CI secret, then set the plain variables. */
export async function configureRepo(
  ctx: GitHubContext,
  answers: Answers,
  infisicalProjectId: string,
): Promise<void> {
  // The workflows map AWS_* (state backend) from the same SCW_* secrets, so
  // each credential is stored once and rotated in one place.
  await setSecrets(ctx, {
    SCW_ACCESS_KEY: answers.scaleway.accessKey,
    SCW_SECRET_KEY: answers.scaleway.secretKey,
    SCW_DEFAULT_PROJECT_ID: answers.scaleway.projectId,
    SCW_DEFAULT_ORGANIZATION_ID: answers.scaleway.organizationId,
    INFISICAL_CLIENT_ID: answers.infisical.clientId,
    INFISICAL_CLIENT_SECRET: answers.infisical.clientSecret,
  });
  await setVariables(ctx, {
    TF_STATE_BUCKET: answers.stateBucket,
    SCW_REGION: answers.region,
    INFISICAL_PROJECT_ID: infisicalProjectId,
    INFISICAL_HOST: answers.infisical.host,
  });
  await configureEnvironments(ctx, answers);
  await protectMainBranch(ctx, answers);
}

async function setSecrets(ctx: GitHubContext, secrets: Record<string, string>): Promise<void> {
  await sodium.ready;
  const { data: key } = await ctx.octokit.actions.getRepoPublicKey({
    owner: ctx.owner,
    repo: ctx.repo,
  });
  for (const [name, value] of Object.entries(secrets)) {
    const sealed = sodium.crypto_box_seal(
      sodium.from_string(value),
      sodium.from_base64(key.key, sodium.base64_variants.ORIGINAL),
    );
    await ctx.octokit.actions.createOrUpdateRepoSecret({
      owner: ctx.owner,
      repo: ctx.repo,
      secret_name: name,
      encrypted_value: sodium.to_base64(sealed, sodium.base64_variants.ORIGINAL),
      key_id: key.key_id,
    });
  }
}

async function setVariables(ctx: GitHubContext, variables: Record<string, string>): Promise<void> {
  for (const [name, value] of Object.entries(variables)) {
    try {
      await ctx.octokit.actions.createRepoVariable({
        owner: ctx.owner,
        repo: ctx.repo,
        name,
        value,
      });
    } catch (error) {
      if ((error as { status?: number }).status !== 409) throw error;
      await ctx.octokit.actions.updateRepoVariable({
        owner: ctx.owner,
        repo: ctx.repo,
        name,
        value,
      });
    }
  }
}

/** Each environment gets a GitHub deployment environment; gated ones (prod) require approval. */
async function configureEnvironments(ctx: GitHubContext, answers: Answers): Promise<void> {
  for (const env of answers.environments) {
    await ctx.octokit.repos.createOrUpdateEnvironment({
      owner: ctx.owner,
      repo: ctx.repo,
      environment_name: env.githubEnvironment,
      ...(env.gated ? { reviewers: [{ type: 'User', id: ctx.ownerId }] } : {}),
    });
  }
}

/** Require a green plan on PRs and forbid force-pushes/deletion of main. */
async function protectMainBranch(ctx: GitHubContext, answers: Answers): Promise<void> {
  await ctx.octokit.repos.updateBranchProtection({
    owner: ctx.owner,
    repo: ctx.repo,
    branch: 'main',
    required_status_checks: {
      strict: false,
      // Matches the job names produced by the plan workflow: "plan (<slug>)".
      contexts: answers.environments.map((env) => `plan (${env.slug})`),
    },
    enforce_admins: false,
    required_pull_request_reviews: null,
    restrictions: null,
    allow_force_pushes: false,
    allow_deletions: false,
  });
}
